import { describe, expect, it } from 'vitest';
import { GuidedObservationController, type GuidedObservationControlAdapter, type GuidedObservationState } from '../../src/presentation/guidedObservationPresets';
const original: GuidedObservationState = Object.freeze({ horizon: false, constellations: false, group: undefined, selected: [], colorMode: 'unified', base: 'deep-violet', highlight: 'observation-orange', strength: 'subtle', axis: true, poleMarkers: true, poleLabels: true, earthCore: true });
function harness() { let state = original; let writes = 0; let refreshes = 0; const adapter: GuidedObservationControlAdapter = { read: () => state, write: (next) => { writes += 1; state = next; }, refresh: () => { refreshes += 1; } }; return { controller: new GuidedObservationController(adapter), state: () => state, writes: () => writes, refreshes: () => refreshes }; }
describe('guided observation live-controller boundary', () => {
  it('applies Local Orientation through one write and refresh without unrelated state', () => { const h = harness(); expect(h.controller.apply('local-orientation')).toBe(true); expect(h.state()).toMatchObject({ horizon: true, constellations: false, selected: [], colorMode: 'unified', axis: false, poleMarkers: false, poleLabels: false, earthCore: false }); expect(h.writes()).toBe(1); expect(h.refreshes()).toBe(1); });
  it('maps exact anchor and circumpolar selections', () => { const h = harness(); h.controller.apply('introduction-anchors'); expect(h.state().selected).toEqual(['ORI', 'UMA', 'CAS']); expect(h.state()).toMatchObject({ constellations: true, group: 'introduction-anchors', colorMode: 'highlight', base: 'celestial-lavender', highlight: 'observation-orange', strength: 'subtle' }); h.controller.apply('north-star-and-circumpolar'); expect(h.state().selected).toEqual(['UMI', 'UMA', 'CAS', 'CEP', 'DRA']); expect(h.controller.canRestore).toBe(true); });
  it('retains the first snapshot and restores once', () => { const h = harness(); h.controller.apply('introduction-anchors'); h.controller.apply('north-star-and-circumpolar'); expect(h.controller.restore()).toBe(true); expect(h.state()).toBe(original); expect(h.controller.activePreset).toBeUndefined(); expect(h.controller.canRestore).toBe(false); const writes = h.writes(); const refreshes = h.refreshes(); expect(h.controller.restore()).toBe(false); expect(h.writes()).toBe(writes); expect(h.refreshes()).toBe(refreshes); });
  it('does not write or refresh for an unknown identifier', () => { const h = harness(); expect(h.controller.apply('unknown')).toBe(false); expect(h.writes()).toBe(0); expect(h.refreshes()).toBe(0); });
  it('clears active status without replacing the original snapshot', () => { const h = harness(); h.controller.apply('introduction-anchors'); h.controller.clearActivePresetPreservingSnapshot(); expect(h.controller.activePreset).toBeUndefined(); expect(h.controller.canRestore).toBe(true); expect(h.controller.restore()).toBe(true); expect(h.state()).toBe(original); });
  it('restores an existing non-orange highlight choice after temporary instruction highlighting', () => { const originalWithCustomHighlight = Object.freeze({ ...original, highlight: 'solar-gold' as const }); let state: GuidedObservationState = originalWithCustomHighlight; const adapter: GuidedObservationControlAdapter = { read: () => state, write: (next) => { state = next; }, refresh: () => undefined }; const controller = new GuidedObservationController(adapter); controller.apply('introduction-anchors'); expect(state.highlight).toBe('observation-orange'); controller.restore(); expect(state).toBe(originalWithCustomHighlight); });
});
